/*
Copyright 2018 (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddonInstanceListerExpansion allows custom methods to be added to
// AddonInstanceLister.
type AddonInstanceListerExpansion interface{}

// AddonInstanceNamespaceListerExpansion allows custom methods to be added to
// AddonInstanceNamespaceLister.
type AddonInstanceNamespaceListerExpansion interface{}

// AddonManifestListerExpansion allows custom methods to be added to
// AddonManifestLister.
type AddonManifestListerExpansion interface{}

// AddonManifestNamespaceListerExpansion allows custom methods to be added to
// AddonManifestNamespaceLister.
type AddonManifestNamespaceListerExpansion interface{}
