apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.serviceAccountName is required" .Values.serviceAccountName }}
  namespace: garden
  labels:
    app: gardener
    role: bouquet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
