/*
Copyright 2018 (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/bouquet/pkg/apis/garden/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAddonInstances implements AddonInstanceInterface
type FakeAddonInstances struct {
	Fake *FakeGardenV1alpha1
	ns   string
}

var addoninstancesResource = schema.GroupVersionResource{Group: "garden.sapcloud.io", Version: "v1alpha1", Resource: "addoninstances"}

var addoninstancesKind = schema.GroupVersionKind{Group: "garden.sapcloud.io", Version: "v1alpha1", Kind: "AddonInstance"}

// Get takes name of the addonInstance, and returns the corresponding addonInstance object, and an error if there is any.
func (c *FakeAddonInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.AddonInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(addoninstancesResource, c.ns, name), &v1alpha1.AddonInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddonInstance), err
}

// List takes label and field selectors, and returns the list of AddonInstances that match those selectors.
func (c *FakeAddonInstances) List(opts v1.ListOptions) (result *v1alpha1.AddonInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(addoninstancesResource, addoninstancesKind, c.ns, opts), &v1alpha1.AddonInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AddonInstanceList{ListMeta: obj.(*v1alpha1.AddonInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.AddonInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested addonInstances.
func (c *FakeAddonInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(addoninstancesResource, c.ns, opts))

}

// Create takes the representation of a addonInstance and creates it.  Returns the server's representation of the addonInstance, and an error, if there is any.
func (c *FakeAddonInstances) Create(addonInstance *v1alpha1.AddonInstance) (result *v1alpha1.AddonInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(addoninstancesResource, c.ns, addonInstance), &v1alpha1.AddonInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddonInstance), err
}

// Update takes the representation of a addonInstance and updates it. Returns the server's representation of the addonInstance, and an error, if there is any.
func (c *FakeAddonInstances) Update(addonInstance *v1alpha1.AddonInstance) (result *v1alpha1.AddonInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(addoninstancesResource, c.ns, addonInstance), &v1alpha1.AddonInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddonInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAddonInstances) UpdateStatus(addonInstance *v1alpha1.AddonInstance) (*v1alpha1.AddonInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(addoninstancesResource, "status", c.ns, addonInstance), &v1alpha1.AddonInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddonInstance), err
}

// Delete takes name of the addonInstance and deletes it. Returns an error if one occurs.
func (c *FakeAddonInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(addoninstancesResource, c.ns, name), &v1alpha1.AddonInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAddonInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(addoninstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AddonInstanceList{})
	return err
}

// Patch applies the patch and returns the patched addonInstance.
func (c *FakeAddonInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AddonInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(addoninstancesResource, c.ns, name, data, subresources...), &v1alpha1.AddonInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddonInstance), err
}
