/*
Copyright 2018 (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/bouquet/pkg/apis/garden/v1alpha1"
	scheme "github.com/gardener/bouquet/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AddonInstancesGetter has a method to return a AddonInstanceInterface.
// A group's client should implement this interface.
type AddonInstancesGetter interface {
	AddonInstances(namespace string) AddonInstanceInterface
}

// AddonInstanceInterface has methods to work with AddonInstance resources.
type AddonInstanceInterface interface {
	Create(*v1alpha1.AddonInstance) (*v1alpha1.AddonInstance, error)
	Update(*v1alpha1.AddonInstance) (*v1alpha1.AddonInstance, error)
	UpdateStatus(*v1alpha1.AddonInstance) (*v1alpha1.AddonInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AddonInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.AddonInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AddonInstance, err error)
	AddonInstanceExpansion
}

// addonInstances implements AddonInstanceInterface
type addonInstances struct {
	client rest.Interface
	ns     string
}

// newAddonInstances returns a AddonInstances
func newAddonInstances(c *GardenV1alpha1Client, namespace string) *addonInstances {
	return &addonInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the addonInstance, and returns the corresponding addonInstance object, and an error if there is any.
func (c *addonInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.AddonInstance, err error) {
	result = &v1alpha1.AddonInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addoninstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AddonInstances that match those selectors.
func (c *addonInstances) List(opts v1.ListOptions) (result *v1alpha1.AddonInstanceList, err error) {
	result = &v1alpha1.AddonInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addoninstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addonInstances.
func (c *addonInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("addoninstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a addonInstance and creates it.  Returns the server's representation of the addonInstance, and an error, if there is any.
func (c *addonInstances) Create(addonInstance *v1alpha1.AddonInstance) (result *v1alpha1.AddonInstance, err error) {
	result = &v1alpha1.AddonInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("addoninstances").
		Body(addonInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a addonInstance and updates it. Returns the server's representation of the addonInstance, and an error, if there is any.
func (c *addonInstances) Update(addonInstance *v1alpha1.AddonInstance) (result *v1alpha1.AddonInstance, err error) {
	result = &v1alpha1.AddonInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addoninstances").
		Name(addonInstance.Name).
		Body(addonInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *addonInstances) UpdateStatus(addonInstance *v1alpha1.AddonInstance) (result *v1alpha1.AddonInstance, err error) {
	result = &v1alpha1.AddonInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addoninstances").
		Name(addonInstance.Name).
		SubResource("status").
		Body(addonInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the addonInstance and deletes it. Returns an error if one occurs.
func (c *addonInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addoninstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addonInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addoninstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched addonInstance.
func (c *addonInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AddonInstance, err error) {
	result = &v1alpha1.AddonInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("addoninstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
